name: test-container
on: [push]

jobs:
  test-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          # builder: ${{ steps.buildx.outputs.name }}
          # platforms: linux/amd64,linux/arm64
          context: .
          load: true
          tags: timarenz/lw-scanner:test

      - name: Check version
        run: docker run timarenz/lw-scanner:test version
