name: test-container
on: [push]

jobs:
  test-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker run debug
        run: docker run --help

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build Docker image (amd64)
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: .
          load: true
          tags: timarenz/lw-scanner:test-amd64

      - name: Check version (amd64)
        run: docker run --platform linux/amd64 timarenz/lw-scanner:test-amd64 version

      - name: Build Docker image (arm64)
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          context: .
          load: true
          tags: timarenz/lw-scanner:test-arm64

      - name: Check version (arm64)
        run: docker run --platform linux/arm64 timarenz/lw-scanner:test-arm64 version
