name: test-container
on: [push]

jobs:
  test-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image (amd64)
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          context: .
          load: true
          tags: lw-scanner:test-amd64

      - name: Check version (amd64)
        run: docker run lw-scanner:test-arm64 version

      - name: Build Docker image (arm64)
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64
          context: .
          load: true
          tags: lw-scanner:test-arm64

      - name: Check version (arm64)
        run: docker run lw-scanner:test-arm64 version
